name: squash
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: 0.5.7+4
  tflite:
  percent_indicator:
  circular_countdown_timer:
  intl:
  eva_icons_flutter:
  outline_material_icons:
  hive:
  hive_flutter:
  hive_generator:
  build_runner:
  matrix_gesture_detector:
  shared_preferences:
  scidart:
  cupertino_icons:
  flutter_swiper:
  custom_clippers:
  page_transition: "^1.1.7+6"
  blobs:
  fl_chart: ^0.20.1
  sliver_header_delegate:
  animated_widgets: ^1.0.6
  animated_icon_button:
  extended_nested_scroll_view:
  cool_alert: ^1.0.3
  tutorial_coach_mark:
  confetti: ^0.5.5
  font_awesome_flutter:
  direct_select: "^1.0.3"
  wakelock: ^0.5.0+2
  flutter_ringtone_player: ^3.0.0
  flutter_beep: ^0.2.0
  soundpool: ^1.1.3




dev_dependencies:

  flutter_native_splash:

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ball.txt
    - assets/converted_model.tflite
    - assets/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/test.jpg
    - assets/target.png
    - assets/ghost_icon.png
    - assets/ssd_mobilenet.tflite
    - assets/ssd_mobilenet.txt
    - assets/info_check.flr
    - assets/sounds/ding.mp4

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#flutter pub run flutter_native_splash:create

flutter_native_splash:
  image: assets/ghost_icon.png
  color: "#42598a"
  color_dark: "#13132e"
  image_dark: assets/ghost_icon.png